/*
 * This file is part of the PageSeeder Bridge API.
 *
 * For licensing information please see the file license.txt included in the release.
 * A copy of this licence can also be found at
 *   http://www.opensource.org/licenses/artistic-license-2.0.php
 */
package org.pageseeder.bridge.xml;

import java.util.ArrayList;
import java.util.List;

import org.pageseeder.bridge.model.PSGroup;
import org.pageseeder.bridge.model.PSResult;
import org.xml.sax.Attributes;
import org.xml.sax.SAXException;
import org.xml.sax.helpers.DefaultHandler;

/**
 *
 * @author Christophe Lauret
 * @version 0.2.2
 * @version 0.1.0
 */
public final class PSResultHandler extends DefaultHandler {

  /**
   * Results generated by this handler.
   */
  private final List<PSResult> _results = new ArrayList<PSResult>();

  /**
   * Text buffer (state variable)
   */
  private StringBuilder buffer = new StringBuilder();

  /**
   * The current group the result is part of.
   */
  private PSGroup group = null;

  /**
   * Result being processed (state variable)
   */
  private PSResult result = null;

  /**
   * Current details field position (state variable)
   */
  private String field = null;

  @Override
  public void startElement(String uri, String localName, String qName, Attributes atts) throws SAXException {
    if ("document".equals(localName)) {
      this.result = new PSResult(this.group);
    } else if ("field".equals(localName)) {
      this.field = atts.getValue("name");
    } else if ("search".equals(localName)) {
      String groupid = atts.getValue("groupid");
      String groupname = atts.getValue("groupname");
      if (groupname != null) {
        this.group = new PSGroup(groupname);
        try {
          this.group.setId(Long.parseLong(groupid));
        } catch (NumberFormatException ex) {
          // Ignore
        }
      }
    }
  }

  @Override
  public void characters(char[] ch, int offset, int len) throws SAXException {
    if (this.field != null) {
      this.buffer.append(ch, offset, len);
    }
  }

  @Override
  public void endElement(String uri, String localName, String qName) throws SAXException {
    if (this.result != null) {
      if ("document".equals(localName)) {
        this._results.add(this.result);
        this.result = null;
      } else if ("field".equals(localName)) {
        this.result.add(new PSResult.Field(this.field, this.buffer.toString()));
        this.buffer.setLength(0);
        this.field = null;
      }
    }
  }

  /**
   * @return the memberships
   */
  public List<PSResult> listResults() {
    return this._results;
  }

}
